name: Windows Build Only

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2
  APP_NAME: "TikTok Views Free"
  PACKAGE_NAME: "com.coderx.tiktokbooster"
  ICON_PATH: "assets/icon.png"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flet  # تأكد من تثبيت flet

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Install Windows Dependencies
      run: |
        choco upgrade chocolatey -y
        choco install -y visualstudio2022buildtools
        choco install -y visualstudio2022-workload-vctools
        flutter doctor

    - name: Enable Flutter Windows Desktop Support
      run: flutter config --enable-windows-desktop

    - name: Flet Build Windows
      shell: powershell
      run: |
        $Env:BUILD_NUMBER="${{ env.BUILD_NUMBER }}"
        $Env:BUILD_VERSION="${{ env.BUILD_VERSION }}"
        flet build windows --name "${{ env.APP_NAME }}" --package "${{ env.PACKAGE_NAME }}" --icon "${{ env.ICON_PATH }}" --verbose --build-number=$Env:BUILD_NUMBER --build-version=$Env:BUILD_VERSION

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-artifact
        path: build/windows
        if-no-files-found: warn
        overwrite: false
